/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @yme/vite-plugin-router-page

declare namespace RouterPage {
  /** 根路由 */
  type RootRouteKey = 'root';

  /** 未找到路由(捕获无效路径的路由) */
  type NotFoundRouteKey = 'not-found';

  /** 页面路由 */
  type RouteKey =
    | 'login'
    | 'about'
    | 'dashboard'
    | 'dashboard_orders'
    | 'dashboard_orders_detail'
    | 'system'
    | 'system_permission'
    | 'system_role'
    | 'system_user'
    | 'users'
    | 'users_[id]'
    | 'users_pro'
    | 'users_pro_file';

  /** 最后一级路由(该级路有对应的页面文件) */
  type LastDegreeRouteKey = Extract<RouteKey, 'login' | 'about' | 'dashboard_orders_detail' | 'dashboard' | 'system_permission' | 'system_role' | 'system_user' | 'users_[id]' | 'users_pro_file'>

  /** route of pages */
  type RoutePaths =
    | '/login'
    | '/about'
    | '/dashboard/orders/detail'
    | '/dashboard'
    | '/system/permission'
    | '/system/role'
    | '/system/user'
    | '/users/:id'
    | '/users/pro_file';

}
