/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @yme/vite-plugin-router-page

// Define your global type AppRouter.Component
export const pages: Record<RouterPage.LastDegreeRouteKey, AppRouter.Component> = {
  'login': () => import('./_buildin/login/page.tsx'),
  'about': () => import('./about/page.tsx'),
  'dashboard_orders_detail': () => import('./dashboard/orders/detail/page.tsx'),
  'dashboard': () => import('./dashboard/page.tsx'),
  'system_permission': () => import('./system/permission/page.tsx'),
  'system_role': () => import('./system/role/page.tsx'),
  'system_user': () => import('./system/user/page.tsx'),
  'users_[id]': () => import('./users/[id]/page.tsx'),
  'users_pro_file': () => import('./users/pro_file/page.tsx'),
};

export const routes: Record<RouterPage.LastDegreeRouteKey, RouterPage.RoutePaths> = {
  'login': '/login',
  'about': '/about',
  'dashboard_orders_detail': '/dashboard/orders/detail',
  'dashboard': '/dashboard',
  'system_permission': '/system/permission',
  'system_role': '/system/role',
  'system_user': '/system/user',
  'users_[id]': '/users/:id',
  'users_pro_file': '/users/pro_file',
};
