/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @yme/vite-plugin-router-page
// Define your global type AppRouter.Component

export const pages: Record<RouterPage.LastDegreeRouteKey, AppRouter.Component> = {
  login: () => import('./_buildin/login/page.tsx'),
  about: () => import('./about/page.tsx'),
  dashboard: () => import('./dashboard/page.tsx'),
  system_permission: () => import('./system/permission/page.tsx'),
  system_role: () => import('./system/role/page.tsx'),
  system_user: () => import('./system/user/page.tsx')
};
